### ISSUE TITLE
Regarding the issue of not being able to detect LICENSE and zenodo linked;

### ISSUE THREAD

**Issue by MiJia-ID** [cthoyt/autoreviewer#10]
Hello author, I am facing the following two questions:
1. When there is an MIT LICENSE file in the root directory of my project, autoreviewer has been unable to detect its existence and reports the issue in the first message:
No, the GitHub license picker can be used to facilitate adding one by following this
link: [ https://github.com/MiJia-ID/ggn-go/community/license/new?branch=main ]( https://github.com/MiJia-ID/ggn-go/community/license/new?branch=main ).
2. In my README.md, the corresponding [! [DOI] has been explicitly added（ https://zenodo.org/badge/818847334.svg )]( https://zenodo.org/doi/10.5281/zenodo.13768952 ）But autoreviewer still cannot detect it and reports a problem in the fourth article:
 Has the repository been externally archived on Zenodo, FigShare, or equivalent that is referenced in the README?
No, this repository has a README, but it does not reference Zenodo. The GitHub-Zenodo integration can be
set up by following [this tutorial]( https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content ).
If your Zenodo record is `XYZ`, then you can use the following in your README:
```markdown
[![DOI]( https://zenodo.org/badge/DOI/10.5281/zenodo.XYZ.svg )]( https://doi.org/10.5281/zenodo.XYZ )
```
The above problem still exists when I use -- no cache to update the latest code

**Comment by cthoyt** [comment]
1. I ran it locally and didn't have an issue with autoreviewer getting the MIT license
2. There's a typo in your markdown for your link, which you should be able to see when you look the README in https://github.com/MiJia-ID/GGN-GO. I sent a PR in https://github.com/MiJia-ID/GGN-GO/pull/1 to fix this
